server:  port: 6060

spring:
  h2:
    console:
      enabled: true
      path: /h2-console/        datasource:    url: jdbc:h2:mem:graphql    driver-class-name: org.h2.Driver    username: ranjith    password: sekar    graphiql:  mapping: /graphiql  endpoint: /graphql  enabled: true  