server:
  port: 8080
  error:
    whitelabel:      enabled: false
      
management:
  server:    port: 8099
  endpoints:
    web:
      base-path: / 
      path-mapping:
           health: health

spring:  application:    name: masterdataservice  data:    mongodb:      host: localhost
      port: 27017
      database: angadi
    
logging:
    level:
      root: info     
      com.angadi.vendor:  INFO
    pattern:
     file:    "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: /logs/masterdataservice.log
    
    