package com.bootrest.common;

public enum SubCategoryName {
  // ELECTRONIC
  MOBILE, LAPTOP, TABLETS,

  // ELECTRICAL
  TELEVISION, FAN,

  // APPLIANCE
  WASHING_MACHINE, AIR_CONDITIONER,

  // BOOK
  EDUCATION, FICTION, NON_FICTION, EXAM,

  // SPORT
  CRICKET, FOORTBALL, BADMINTON,;
}
